spring:
  application:
    name: AEON-Backend
  datasource:
    url: 'jdbc:postgresql://localhost:5432/aeon-rest-api'
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: '8080'
springdoc:
  api-docs:
    path: /v1/docs/api
  swagger-ui:
    path: /v1/docs/api-ui.html
